version: '3.8'

services:
  app:
    build: .
    ports:
      - 3313:3313
    environment:
      - PORT=3313 # Used by react
      - DANGEROUSLY_DISABLE_HOST_CHECK=true

networks:
  default:
    name: wasmiot-net
    driver: bridge
    external: true
