version: '3.8'

services:
  webgui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - "8080:8080"
    command: poetry run uvicorn --host=0.0.0.0 --port=8080 app.app:app
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: wasmiot-net
