version: '3.8'

services:
  app:
    build: .
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}" # Frontend server
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - PORT=${FRONTEND_PORT}

networks:
  default:
    name: wasmiot-net
    driver: bridge
